apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-remote
  namespace: default
spec:
  releaseName: cloudflare-tunnel-remote
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      sourceRef:
        kind: HelmRepository
        name: wrsys
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    secretName: cloudflare-tunnel-remote