# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: acme
# spec:
#   acme:
#     # Replace the email address with your own contact email
#     email: mark.bluhm@gmail.com
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: acme
#     solvers:
#       - http01:
#           ingress:
#             ingressClassName: traefik