apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    configuration:
      enabled: true
      trusted_proxies: [ "10.42.0.0/16" ]
    ingress:
      external: true
    persistence:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
